spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      # floor((max_connections - superuser_reserved - 운영여유) / ASG_max / JVM수 / 풀수)
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000      # 10m
      max-lifetime: 1800000     # 30m
      keepalive-time: 300000    # 5m

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          use_get_generated_keys: true
          statement_cache_size: 0

sentry:
  dsn: ${PROD_SENTRY_DSN}
  environment: prod

server:
  forward-headers-strategy: native

security:
  cookie:
    dev-mode: false

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off

swagger:
  server-url: https://api.cchaksa.com
